### PR TITLE
Support dart analysis_server

### PR DESCRIPTION
**Pull request by wordijp**
dart-sdk is provides analysis_server, LSP is using it.
The script in servers directory is generate by myself.

### CODE REVIEW

**Comment by mattn** [comment]
You can download dart-sdk from:

https://dart.dev/tools/sdk/archive

**Comment by mattn** [comment]
Could you please try my PR? https://github.com/mattn/vim-lsp-settings/pull/58

**Comment by wordijp** [comment]
PR(#58) is thanks,  looks good but needs some modification.
(`%~dp0\run_unzip.cmd`  and
`%~dp0\dart-sdk\bin\dart %~dp0\dart-sdk\bin\snapshots\analysis_server.dart.snapshot --lsp %*`)

but, I want to use the installed dart-sdk, because dart-sdk is already included when installing `dart` or `flutter`, and file size is large, and many files other than analysis_server.
please see [natebosch/vim-lsc-dart: dart.vim:s:FindDart()](https://github.com/natebosch/vim-lsc-dart/blob/master/autoload/lsc/dart.vim#L48), and [Dart-Code/Dart-Code: utils.ts:findDartSdk()](https://github.com/Dart-Code/Dart-Code/blob/master/src/extension/sdk/utils.ts#L278), these are also starting `analysis_server` from using installed dart.

And sorry, this PR had a bug. need resolved path for symbolic links.
for ubuntu

```
$ which dart
/usr/bin/dart
$ readlink $(which dart)
../lib/dart/bin/dart
```

**Comment by mattn** [comment]
You don't need make new installer for your use-case if you want to use installed dart-sdk. If my PR will be merged, you can  do it with small configuration to enable installed dart-sdk.

```vim
let g:lsp_settings = {
\ 'analysis_server.dart.snapshot': {'cmd': ['/path/to/your/dart-sdk/bin/dart', '/path/to/your/dart-sdk/bin/bin/snapshots/analysis_server.dart.snapshot', '--lsp']}
\}
```

**Comment by wordijp** [comment]
OK, I do it, thanks.

**Comment by jmdevin** [comment]
I'd like to recommend we put those settings at the bottom of the README in that configuration section, or a separate wiki or help section. I installed this plugin and it took me a while to figure out why it wasn't automatically using my already-installed dart server. It works with the settings now, but I don't think I saw it stated clearly anywhere that this will only use the server if it's itself in the path.

**Comment by mattn** [comment]
The way to specify the path to the already-installed server about clangd.

https://github.com/mattn/vim-lsp-settings#configurations

Could you please send me pull-request?

**Comment by jmdevin** [comment]
Yeah I should be able to.

**Pull request closed without merging**
