### PR TITLE
Fix install-rust-analyzer.sh

### PR DESCRIPTION
**Pull request by lnsf**
Fixed wrong download binary name.

### CODE REVIEW

**Comment by johejo** [comment]
Hi, better to delete the file about ra_lsp_server, too.
Both the name of the binary and the name of the tool are now rust-analyzer.
https://github.com/rust-analyzer/rust-analyzer/pull/3216

**Comment by prabirshrestha** [comment]
Also should update .cmd file for windows.

**Comment by lnsf** [comment]
Thank you for your response.  
``` installer/install-rust-analyzer.cmd``` seems already correct.  
What kind of update should I do? @prabirshrestha

**Comment by mattn** [comment]
Please remove entry of ra_lsp_server from settings.json

**Comment by mattn** [comment]
Thank you.

**Pull request merged**
