### PR TITLE
Add LspSwitchSourceHeader based on @kent-tri's patch

### PR DESCRIPTION
**Pull request by mattn**
See https://github.com/prabirshrestha/vim-lsp/pull/703

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Header seems specific to c. Should it be called Alternate instead?

Not sure if other language has it.

No strong preference here.

**Comment by mattn** [comment]
@kent-tri What thought about naming?

**Comment by kent-tri** [comment]
@mattn @prabirshrestha I would stick with the name that `clangd` uses as it is specific to that language server as well as being specific to the C family of languages. But, I have no strong preference either.

https://clang.llvm.org/extra/clangd/Extensions.html

**Comment by kent-tri** [comment]
Since this is outside the `vim-lsp` plugin now, should there be a check to confirm that `vim-lsp` is installed before executing the commands that rely on it?

**Comment by mattn** [comment]
Finally,  I renamed it to `:LspDocumentSwitchSourceHeader` since vim-lsp use `Lsp` + `Document` + method names.

**Pull request merged**
