### PR TITLE
Added Hyuga installer

### PR DESCRIPTION
**Pull request by sakuraiyuta**
This PR adds Hy Language Server for Hy 0.24.0.

https://github.com/sakuraiyuta/hyuga

### CODE REVIEW

**Comment by mattn** [comment]
Thanks your contribution. Why don't you use pip_install.cmd ?

**Comment by sakuraiyuta** [comment]
@mattn Thank you for reply.

> Could you please explain why `--system-site-package` is required?

`Hyuga` supports to search system installed packages. This feature needs to use `--system-site-package`.
In my opinion, some python developer want to use them.
(Yes, it's so dirty...but a way for users can dare to select.)

It seems no methods to path through option arguments to `pip_install.{sh,cmd}`, so I avoided to use `pip_install` script.
Any ideas? Or should drop it?

Other way: Add options to lsp settings in `initialize`, e.g. `additional-path: {system installed packages dir}` like `root-uri`.

**Comment by mattn** [comment]
Thanks. So could you please update README `Local Install` to No? (If my understainding is right)

**Comment by mattn** [comment]
Now ready to merge this?

**Comment by sakuraiyuta** [comment]
Sorry for waiting you...ready now!

**Comment by mattn** [comment]
Thank you!!

**Pull request merged**
