### PR TITLE
fix: Fix bash throws bad interpreter error by fix commit about #126

### PR DESCRIPTION
**Pull request by nyarla**
[This commit](https://github.com/mattn/vim-lsp-settings/pull/127/commits/a95b48fd4c275b64a153adf8455714228f733151) is using bash as execute shell for installer scripts, but this fix make new probrem about installer scripts throws `Bad Interpreter` error if `/bin/bash` does not exists.

My pull request is changed shebang to `#!/usr/bin/env bash`, and this code is fixed about `Bad Interpreter` error.

BTW, I think that my pull request does not care of bash is not installed.
So I suggest adding notes about runtime dependences to README?

### CODE REVIEW

**Comment by mattn** [comment]
Probably, replacing `bash -c xxx.sh` to `bash xxx.sh` will fix this issue.

**Comment by nyarla** [comment]
@mattn I tried replaces`bash -c` to `bash` inside vim script, but **it's not fixed some cases** .

For example, `installer/install-vim-language-server.sh` calls `installer/npm_install.sh`, if only replaced `bash -c` to `bash` inside vim script, it does not fixed `installer/npm_install.sh` throws `Bad Interpreter` error.

I think that nearly case about installer scripts calls another scripts, called script probably throws `Bad interpreter` error without changes shebang.

**Comment by mattn** [comment]
Make sense. Okay, will merge this. Could you please add revert of https://github.com/mattn/vim-lsp-settings/commit/9a95bf72eca2c0da2585a7fb3b4361ba230e425f into this pull-request?

**Comment by nyarla** [comment]
Okay, I'm (maybe) done it.

**Comment by mattn** [comment]
Thanks!

**Pull request merged**
