### PR TITLE
update html-languageserver (except on windows)

### PR DESCRIPTION
**Pull request by micchy326**
vscode-html-languageserver-bin is very old.
It cannot use "textDocument/rangeFormatting".
This pull request makes it possible.

NOTE: vscode-html-languageserver is not support "textDocument/formatting". It support only "textDocument/rangeFormatting".

### CODE REVIEW

**Comment by mattn** [comment]
Pleaes do NOT close this yet. I want to hear anyone's opinions. Thanks.

**Comment by prabirshrestha** [comment]
What does vscode use?

**Comment by micchy326** [comment]
vscode is using this  repository.
  - https://github.com/microsoft/vscode/commits/master/extensions/html-language-features/server

And this repository is its (auto?) copy
  - https://github.com/vscode-langservers/vscode-html-languageserver

**Comment by prabirshrestha** [comment]
Few random thoughts:

1. Use depth=1 flag when cloning
2. File an issue in upstream repo asking them to release a non package
3. Not a fan a random master downloads. We should try stable commits if possible with tags.

**Comment by micchy326** [comment]
> 1. Use depth=1 flag when cloning

OK, I fixed it.

> 2. File an issue in upstream repo asking them to release a non package

vscode-html-languageserver-bin repo has version update pull request. but no reply.
https://github.com/vscode-langservers/vscode-html-languageserver-bin/pull/7
> 3. Not a fan a random master downloads. We should try stable commits if possible with tags.

Sorry. I couldn't find stable version.
There is a stable version of the vscode repository, but I don't want to clone that repository because it is large.

**Comment by johejo** [comment]
Hi, thanks cool contribution, below is my little idea.
Also npm cli suports installing from GitHub repo directly.
https://docs.npmjs.com/cli/install
How about forking `vscode-langservers/vscode-html-languageserver` as your repo and patch your commit?
And, push your branch and the installer(in vim-lsp-settings) refer it.

**Comment by mattn** [comment]
Sorry delay. It seems that some packages provided from vscode have breaking changes. Now "-bin" packages became not working. We want to switch to use upstream of html-language-server and json-languageserver. Could you please fix conflict?

**Comment by MindTooth** [comment]
What about https://github.com/hrsh7th/vscode-langservers-extracted/?

**Comment by mattn** [comment]
Now switched to [vscode-langservers-extracted/](https://github.com/hrsh7th/vscode-langservers-extracted/).

https://github.com/mattn/vim-lsp-settings/pull/521

Thanks.

**Pull request closed without merging**
