### PR TITLE
fix: add --issues-exit-code=1 flag to `golangci-lint-langserver`

### PR DESCRIPTION
**Pull request by tMinamiii**
I pull requested and merged add default option flag `--issues-exit-code=1 ` to golangci-lint-langserver .
https://github.com/nametake/golangci-lint-langserver/pull/23

This PR  add  `--issues-exit-code=1` to golangci-lint-langserver initialization_options.

### CODE REVIEW

**Comment by mattn** [comment]
Thank you. As far as I can see, this change is breaking compatibility. The users who use older version of golangci-lint-langserver will get errors with this update of vim-lsp-settings. Of course they can work around the problem by do `:LspInstallServer golangci-lint-langserver` again. But I would like to put this as a note https://github.com/mattn/vim-lsp-settings#notes.

Could you please add note in README?

I want to add comment how to use older version with newer vim-lsp-settings

```
:LspSettingsGlobalEdit
```
and edit entry.
```
    "golangci-lint-langserver": {
        "initialization_options": {
            "command": [
                "golangci-lint", "run", "--enable-all", "--disable", "lll", "--out-format", "json"
            ]
        }
    }
```

**Comment by tMinamiii** [comment]
Thank you advice and add configuration note for older version `golangci-lint` user.
Would you please check my message? I am not confident in my English. sorry.

**Comment by mattn** [comment]
Thank you

**Comment by tMinamiii** [comment]
thx merge 😄

**Pull request merged**
