### PR TITLE
add files

### PR DESCRIPTION
**Pull request by aavitiacat**
settings/awk-language-server.vim

### CODE REVIEW

**Comment by aavitiacat** [comment]
$HOME/.local/share/vim-lsp-settings/servers
If you define $XDG_DATA_HOME:

$XDG_DATA_HOME/vim-lsp-settings/servers

**Comment by aavitiacat** [comment]
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
:LspInstallServer

**Comment by aavitiacat** [comment]
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'

**Comment by aavitiacat** [comment]
https://github.com/prabirshrestha/vim-lsp/blob/69e6340c48571cc813c52d6acc2057b8aea6e742/autoload/lsp.vim#L408
7083622140 #1324 
.github/workflows/linux_vim.yml

**Review by aavitiacat — COMMENTED** [review]
settings.json
settings/awk-language-server.vim

**Review by aavitiacat — COMMENTED** [review]
settings.json

**Review by aavitiacat — COMMENTED** [review]
settings/awk-language-server.vim

**Review by aavitiacat — COMMENTED** [review]
settings.json

**Comment by aavitiacat** [comment]
settings.json

**Comment by mattn** [comment]
Sorry, please make PR with clear description.

**Pull request closed without merging**
