### PR TITLE
Update pip before install

### LINKED ISSUE #70: error: invalid command 'bdist_wheel' when install pyls
but after install , pyls can work, Does this error have any effect ?
```
  Running setup.py bdist_wheel for future ... error
  Complete output from command /home/fcying/.vim/.cache/lsp_settings/pyls/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-laf3r_xx/future/setup.py';f=getattr(tokenize, 'open', op
en)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-3vshusay --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for future
  Running setup.py clean for future
Failed to build future
Installing collected packages: ujson, parso, jedi, more-itertools, zipp, importlib-metadata, pluggy, future, python-jsonrpc-server, python-language-server
  Running setup.py install for future ... done
Successfully installed future-0.18.2 importlib-metadata-1.3.0 jedi-0.15.2 more-itertools-8.0.2 parso-0.5.2 pluggy-0.13.1 python-jsonrpc-server-0.3.2 python-language-server-0.31.4 ujson-1.35 zipp-0.6.0
```

### PR DESCRIPTION
**Pull request by mattn**
Fixes #70

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Would this require sudo?

**Comment by prabirshrestha** [comment]
Or might be check pip version?

**Comment by mattn** [comment]
This is local installation. So sudo is not required.

**Comment by prabirshrestha** [comment]
Looks good.

**Pull request merged**
