### PR TITLE
Fix pip cmd

### PR DESCRIPTION
**Pull request by Milly**
* Use `python -m pip ...` instead `pip ...`.
* Do not use `--user`, it's does not upgraded pip in venv.
* Echo running commands for improve log.

### CODE REVIEW

**Comment by mattn** [comment]
Thanks. I prefer to use lowercase `rem`.

**Comment by Milly** [comment]
> Thanks. I prefer to use lowercase `rem`.

Changes all `REM` to `rem`? (include other than the lines I changed?)

**Comment by Milly** [comment]
*installer\install-clangd.cmd* contains `REM`.

**Comment by mattn** [comment]
Okay, I'll do it my-self. Thank you.

**Pull request merged**
